name: Frontend CI

# Triggers the workflow on push, pull request, and manual dispatch
on:
  push:
    branches: [ "main", "master" ]
  pull_request:

  # Enables manual run button in the GitHub Actions tab
  workflow_dispatch:

jobs:


  frontend-fedora:
    runs-on: fedora-latest
    defaults:
      run:
        working-directory: ./Frontend

    steps:
      - name: Install Node.js and Git
        run: |
          dnf -y update
          dnf -y install nodejs npm git

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build and Type Check
        run: npm run build
